### ISSUE TITLE
Further development?

### ISSUE THREAD

**Issue by ujh** [carllerche/hamcrest-rust#23]
I'm currently using this crate (in combination with [stainless](https://github.com/reem/stainless)) and I really enjoy it. Sometimes however I feel that there's a matcher missing. Before I start writing the missing matchers I wanted to ask if it even makes sense, i.e. if this repo is still in active development and if my PRs would be even merged.

And if this is not the case then I wonder if there's any way I could help out with the maintenance. I just started helping with stainless and I think it would make sense to help out here as well.

**Comment by carllerche** [comment]
Sorry for the delay! Help is much appreciated. I have granted you access to the repo :) As you get started, you can ping me in the #mio IRC channel on the mozilla IRC server. Also if you want, you can write PRs and I can check them over for feedback.

**Comment by ujh** [comment]
Thank you so much! 👍
