### ISSUE TITLE
Switch assert_that to a macro

### ISSUE THREAD

**Issue by carllerche** [carllerche/hamcrest-rust#27]
I think that `assert_that` would work better as a macro (to get correct line errors, etc...).

@ujh If this is something that you are OK w/ I can try to work on this next week.

**Comment by ujh** [comment]
It still is your project. Just have a look at how little I've done until now. 😆 I guess  never noticed the issue as my tests normally only contain a few lines of code and it's clear where the failure comes from. But I can see how this wouldn't be ideal.

Things that pop into my mind here:

* Will just `assert_that` be turned into a macro? Or does the rest turn into macros as well? 
* Would it be possible to just have an `assert_that!` macro in addition to the normal function? I imagine that you "just" want to pass `line!` and `file!` to the underlying function and use it to display on error. 
* How complicated will this make the use statements? I assume it would just add one line to the crate's top level file?

**Comment by carllerche** [comment]
I think just `assert_that` would be the macro. It *may* be possible to keep a fn as well, but it won't be useful standalone anymore (since you won't pass line / file in yourself)

I think statements would just become:

```rust

#[macro_use]
extern crate hamcrest;

use hamcrest::equal_to;

assert_that!(foo, equal_to(bar));
```

**Comment by ujh** [comment]
Sounds good. 👍

**Comment by ujh** [comment]
Check out what https://github.com/zummenix/expectest is doing in that space as well.

**Comment by carllerche** [comment]
Yeah, it looks very similar. I only did a quick skim, but personally I'm not a fan of the style:

```rust
expect!(blah).to(be_blah());
```

adds a lot of unnecessary noise to be "english", and it is worse w/ rust compared to something like ruby because ruby can get rid of the parens.

Compared w/

```rust
assert_that!(blah, is_blah());
```

Second thing, the match trait:

```rust
pub trait Matcher<A, E> {
    /// Returns a failure message.
    fn failure_message(&self, join: Join, actual: &A) -> String;

    /// Checks if an actual value matches an expected value.
    fn matches(&self, actual: &A) -> bool;
}
```

I considered doing this w/ Hamcrest, the issue becomes that you end up having to implement the matching logic twice. First to do the match, second to generate the failure message. This is why this lib only has a `match` fn and returns a `Result<(), String>`.

**Comment by ujh** [comment]
Ah, I think I need to practice to be clearer with my comments on open source projects. :)

What I meant is that I should check out what special features they have for the nightly build. Obviously we don't want to switch the syntax. What would be the point of two libraries with do the same thing and look the same as well?
