### ISSUE TITLE
publish a new version with proper license

### ISSUE THREAD

**Issue by semarie** [carllerche/hamcrest-rust#40]
is it possible to publish on crates.io a new version of hamcrest in order to include the new license ?

Currently, crates.io interface announce MIT, but downloaded archive contains no mention of any license. 

Additionnally, the `Cargo.toml` file in hamcrest repository mentions:
 - version "0.1.0"
 - license "MIT/Apache-2.0"

whereas the published "0.1.0" haven't this information.

Publishing a new version would permit to clarify the situation.
Thanks.

**Comment by ujh** [comment]
Yes! That is a very good idea. I think I'll manage to release a new version next week.

**Comment by ujh** [comment]
Done!
